name: Base Java

on:
  workflow_call:
    inputs:
      maven-snapshots:
        description: "Defines if a snapshot build should be published to maven"
        default: false
        required: false
        type: boolean
      maven-private:
        description: "True to publish maven artifacts to the private repository"
        default: false
        required: false
        type: boolean
      java-version:
        description: "The java version"
        default: 17
        required: false
        type: number
      gradle-tasks:
        description: "tasks the gradle action should run"
        default: build
        required: false
        type: string
    secrets:
      ftb-maven-token:
        required: false
      saps-token:
        required: false
      curse-token:
        required: false
      github-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - name: Run gradle tasks [${{ inputs.gradle-tasks }}]
        run: ./gradlew ${{ inputs.gradle-tasks }}
        env:
          SNAPSHOT: ${{ inputs.maven-snapshots }}
          FTB_PRIVATE: ${{ inputs.maven-private}}
          SAPS_TOKEN: ${{ secrets.saps-token }}
          FTB_MAVEN_TOKEN: ${{ secrets.ftb-maven-token }}
          CURSEFORGE_KEY: ${{ secrets.curse-token }}
          TAG: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
