name: Base Java

on:
  workflow_call:
    inputs:
      is-snapshot:
        description: "Defines if this is a snapshot build"
        default: false
        required: false
        type: boolean
      java-version:
        description: "The java version"
        default: 21
        required: false
        type: number
    secrets:
      ftb-maven-token:
        required: false
      curse-token:
        required: false
      modrinth-token:
        required: false
      github-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: ${{ inputs.java-version }}
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Setup Gradle and Validate Wrapper
        uses: gradle/actions/setup-gradle@v4
        # TODO: Better caching setup.
        with:
          cache-read-only: false
      # Prepare a changelog if we're not building a snapshot
      - name: Prepare changelog
        run: ./gradlew prepareChangelog
        if: ${{ !inputs.is-snapshot }}
      - name: Create tasks list
        run: |
          TASKS="build publish"
          # Only publish to platforms if we're not a snapshot
          if [ "${{ inputs.is-snapshot }}" = "false" ]; then
            TASKS="$TASKS publishMods"
          fi
          echo "TASKS=$TASKS" >> $GITHUB_ENV
      - name: Run gradle tasks
        run: ./gradlew ${{ env.TASKS }}
        env:
          SNAPSHOT: ${{ inputs.is-snapshot }}
          FTB_MAVEN_TOKEN: ${{ secrets.ftb-maven-token }}
          # @deprecated don't use this one anymore!
          CURSEFORGE_KEY: ${{ secrets.curse-token }}
          CURSEFORGE_TOKEN: ${{ secrets.curse-token }}
          MODRINTH_TOKEN: ${{ secrets.modrinth-token }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
      - name: Create tag
        if: ${{ !inputs.is-snapshot }}
        run: |
          VERSION=$(./gradlew getRootVersion | grep 'projectVersion=' | sed 's/.*=//')
          git tag "v$VERSION"
          git push origin "v$VERSION"
      - name: Bump version
        if: ${{ !inputs.is-snapshot }}
        # Get the properties.gradle, fetch the mod_version, bump the minor / final dot version, commit the change
        run: |
          VERSION=$(grep 'mod_version' gradle.properties | sed 's/.*=//')
          echo "Current version: $VERSION"
          # Bump the version
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          echo "New version: $NEW_VERSION"
          # Update the gradle.properties
          sed -i "s/mod_version=$VERSION/mod_version=$NEW_VERSION/" gradle.properties
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "[ci-skip] Bump version to $NEW_VERSION"
